# Generated by Django 3.0.3 on 2020-03-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='assetgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ruva.AssetGroup'),
        ),
    ]
