# Generated by Django 3.0.3 on 2020-03-15 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruva', '0002_auto_20200315_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
    ]
